In [45]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
import numpy as np
import pandas as pd
import pickle as pkl
import matplotlib.pyplot as plot

In [46]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape = [19]))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(8, activation='relu'))
model.add(tf.keras.layers.Dense(4, activation='relu'))
model.add(tf.keras.layers.Dense(2, activation=tf.nn.softmax))
model.compile(optimizer=tf.keras.optimizers.Adam(), loss =tf.keras.losses.BinaryCrossentropy(), metrics=['accuracy'])
# callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=50)]

In [47]:
x_test = pkl.load(open('../code/GER_test.pkl' ,'rb'))
y_test = pkl.load(open('../code/GER_test_y.pkl', 'rb'))
x_train_main = pkl.load(open('../code/GER_train.pkl', 'rb'))
y_train_main = pkl.load(open('../code/GER_train_y.pkl', 'rb'))

In [48]:
new_sets = pkl.load(open('./c_validation.pkl', 'rb'))

Model - 1

In [49]:
x_train = new_sets[0]['training']
y_train = new_sets[0]['labels']
x_validate = new_sets[0]['validation']
y_validate = new_sets[0]['validation_labels']

In [50]:
# model.fit(x_train, y_train, epochs=200, validation_data=(x_validate, y_validate))

In [56]:
i = x_validate[0]
print(x_train_main)

[[0.04631804 0.14190991 0.08418234 ... 0.3600657  0.32142857 0.5       ]
 [0.07397126 0.0878519  0.07133727 ... 0.19447861 0.67857143 0.5       ]
 [0.03770867 0.06151615 0.02738048 ... 0.20603255 0.15909091 0.16853933]
 ...
 [0.10647534 0.13753633 0.06430933 ... 0.37192569 0.2745098  0.38961039]
 [0.04122387 0.04372108 0.04135551 ... 0.08562723 0.11764706 0.12987013]
 [0.15451053 0.12892201 0.11704483 ... 0.36913921 0.60784314 0.48051948]]


In [63]:
for j in x_train_main:
    if(j.all() == i.all()):
        print(i)

[ 0.04631804  0.14190991  0.08418234  0.38332878  0.13956291  4.50351958
 -1.40879469  6.64747499  0.61780194  0.09405221  0.08239493  0.06977664
  0.02358857  4.42688723 -0.16426972  2.08303284  0.3600657   0.32142857
  0.5       ]
[ 0.04631804  0.14190991  0.08418234  0.38332878  0.13956291  4.50351958
 -1.40879469  6.64747499  0.61780194  0.09405221  0.08239493  0.06977664
  0.02358857  4.42688723 -0.16426972  2.08303284  0.3600657   0.32142857
  0.5       ]
[ 0.04631804  0.14190991  0.08418234  0.38332878  0.13956291  4.50351958
 -1.40879469  6.64747499  0.61780194  0.09405221  0.08239493  0.06977664
  0.02358857  4.42688723 -0.16426972  2.08303284  0.3600657   0.32142857
  0.5       ]
[ 0.04631804  0.14190991  0.08418234  0.38332878  0.13956291  4.50351958
 -1.40879469  6.64747499  0.61780194  0.09405221  0.08239493  0.06977664
  0.02358857  4.42688723 -0.16426972  2.08303284  0.3600657   0.32142857
  0.5       ]
[ 0.04631804  0.14190991  0.08418234  0.38332878  0.13956291  4.5035